version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: robobo/circleci-buildkit

    working_directory: ~/repo

    steps:
      - checkout
      - run: buildctl build --frontend dockerfile.v0 --local context=~~/repo --local dockerfile=~/repo
